- name: Copy isucondition files
  ansible.builtin.copy:
    src: "../webapp/{{ item }}"
    dest: "/home/isucon/webapp/{{ item }}"
    mode: "0644"
    owner: isucon
    group: isucon
  with_items:
    - go/
